{
 "title": "Stock Trader Online New",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   {
    "name": "business_criticality",
    "label": "Business Criticality",
    "query": "1 - most critical,2 - somewhat critical,3 - less critical,4 - not critical"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "ci",
    "label": "CI Name",
    "query": {}
   },
   { "name": "aggregationType", "query": "app,service" }
  ]
 },
 "panels": [
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "service": "$service",
     "source": "$class"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "memory_used_percent_1",
     "metricSource": "$source",
     "selectedMetricNameList": { "label": "memory_used_percent_1", "value": "memory_used_percent_1" },
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": { "label": "Stock Trader Online", "value": "Stock Trader Online" },
     "selectedSourceList": [
      { "label": "product-docker-node", "value": "product-docker-node" }
     ],
     "service": "$service",
     "source": "$ci"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "metricName": "cpu_utilization_percent_1",
     "metricSource": "$source",
     "selectedMetricNameList": { "label": "cpu_utilization_percent_1", "value": "cpu_utilization_percent_1" },
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "/.*docker-node.*/"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricName": "api_response_time_ms_2",
     "metricSource": "$source",
     "selectedAlertFilterList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedMetricNameList": { "label": "api_response_time_ms_2", "value": "api_response_time_ms_2" },
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$ci"
    },
    {
     "metricName": "errors_count",
     "metricSource": "/inventory-.*/",
     "selectedMetricNameList": { "label": "errors_count", "value": "errors_count" },
     "selectedQueryCategory": { "description": "Get Timeseries metrics", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "/purchase-docker.*/"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "metricName": "$metricName",
     "metricSource": "$source",
     "metricType": "$metricType",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Get Alerts at the Service level",
      "label": "Service",
      "value": "Service"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "source": "/customer-docker-node/"
    }
   ]
  }
 ]
}