{
 "title": "Linux Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ci",
    "query": "61bc01b6db67b010961521fb13961938"
   },
   {
    "name": "kpis",
    "query": {}
   },
   {
    "name": "ciName",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   },
   {
    "name": "ip",
    "query": {}
   },
   {
    "name": "metrics",
    "query": {}
   },
   {
    "name": "anomalyCIS",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 1 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Linux Details</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Linux Servers",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": null
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "asset.display_name", "label": "Asset => Display name", "value": "asset.display_name" },
      { "description": "classification", "label": "Classification", "value": "classification" },
      { "description": "correlation_id", "label": "Correlation ID", "value": "correlation_id" },
      { "description": "cpu_core_count", "label": "CPU core count", "value": "cpu_core_count" },
      { "description": "cpu_name", "label": "CPU name", "value": "cpu_name" },
      { "description": "cpu_speed", "label": "CPU speed (MHz)", "value": "cpu_speed" },
      { "description": "default_gateway", "label": "Default Gateway", "value": "default_gateway" },
      { "description": "discovery_source", "label": "Discovery source", "value": "discovery_source" },
      { "description": "dns_domain", "label": "DNS Domain", "value": "dns_domain" },
      { "description": "disk_space", "label": "Disk space (GB)", "value": "disk_space" },
      { "description": "firewall_status", "label": "Firewall status", "value": "firewall_status" },
      { "description": "fqdn", "label": "Fully qualified domain name", "value": "fqdn" },
      { "description": "ip_address", "label": "IP Address", "value": "ip_address" },
      { "description": "kernel_release", "label": "Kernel Release", "value": "kernel_release" },
      { "description": "object_id", "label": "Object ID", "value": "object_id" },
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "os", "label": "Operating System", "value": "os" },
      { "description": "os_version", "label": "OS Version", "value": "os_version" },
      { "description": "ram", "label": "RAM (MB)", "value": "ram" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "virtual", "label": "Is Virtual", "value": "virtual" },
      { "description": "host_name", "label": "Host name", "value": "host_name" }
     ],
     "tableName": { "description": "cmdb_ci_linux_server", "label": "Linux Server", "value": "cmdb_ci_linux_server" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_class_name", "label": "Configuration Item => Class", "value": "ci_id.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_linux_server", "value": "cmdb_ci_linux_server" },
       "4": null
      },
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_class_name", "label": "Host => Class", "value": "cmdb_ci.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_linux_server", "value": "cmdb_ci_linux_server" },
       "4": null
      },
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "agent_version", "label": "Version", "value": "agent_version" }
     ],
     "tableName": { "description": "sn_agent_ci_extended_info", "label": "Agent Client Collector Info", "value": "sn_agent_ci_extended_info" }
    }
   ]
  },
  {
   "title": "[ $ciName ] Logs / Minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": null,
       "2": null,
       "3": null,
       "4": null
      }
     ],
     "elasticSearch": "raw_message: $ciName",
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
     "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
     "trendPeriod": "1"
    }
   ]
  },
  {
   "title": "Anomaly insights",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {
       "1": null,
       "2": null,
       "3": null,
       "4": null
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "rowLimit": "10",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=Closed^group_source=9",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$anomalyCIS", "value": "$anomalyCIS" },
       "4": null
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "sys_class_name", "label": "Class", "value": "sys_class_name" }
     ],
     "tableName": { "description": "cmdb_ci", "label": "Configuration Item", "value": "cmdb_ci" }
    }
   ]
  },
  {
   "title": "Log Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "raw_message: $ciName AND access",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": null,
         "2": null,
         "3": null,
         "4": null
        }
       ],
       "elasticSearch": "raw_message: $ciName AND access",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    },
    {
     "title": "raw_message: $ciName AND error",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": null,
         "2": null,
         "3": null,
         "4": null
        }
       ],
       "elasticSearch": "raw_message: $ciName AND error",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$cis", "value": "$cis" },
         "4": null
        },
        {
         "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$supportGroup", "value": "$supportGroup" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_class_name=cmdb_ci_linux_server^cmdb_ci=$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metrics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "repeat": "metrics",
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": null,
         "2": null,
         "3": null,
         "4": null
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$metrics", "value": "$metrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Software Installations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 15 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Software on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_software_instance", "label": "Software Instance", "value": "cmdb_software_instance" }
      }
     ]
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 16 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Running Processes on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_running_process", "label": "Running Process", "value": "cmdb_running_process" }
      }
     ]
    }
   ]
  },
  {
   "title": "Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Changes (last 7 days)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_class_name=cmdb_ci_linux_server^sys_created_on>=javascript:gs.beginningOfLast7Days()^cmdb_ci=$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$kpis",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "repeat": "kpis",
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" },
         "4": null
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        { "label": "$kpis", "value": "$kpis" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}