{
 "title": "ACC CI 360 Degree View",
 "time": { "from": "2022-07-15T03:44:14.016Z", "to": "2022-07-26T22:14:14.049Z" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "Metric KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$ci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 1 },
   "options": {
    "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-vcard\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">CI Attributes</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ciClasses",
      "value": "$ciClasses"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the OS", "label": "OS", "value": "OS" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "cmdb_ci.sys_class_name", "label": "Host => Class", "value": "cmdb_ci.sys_class_name" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "running_checks_num", "label": "Number of running checks", "value": "running_checks_num" },
      { "description": "data_collection", "label": "Data Collection", "value": "data_collection" },
      { "description": "agent_version", "label": "Version", "value": "agent_version" },
      { "description": "ip_address", "label": "IP address", "value": "ip_address" },
      { "description": "cmdb_ci.last_discovered", "label": "Host => Most recent discovery", "value": "cmdb_ci.last_discovered" },
      {
       "description": "cmdb_ci.fqdn",
       "label": "Host => Fully qualified domain name",
       "value": "cmdb_ci.fqdn"
      },
      { "label": "cmdb_ci.os", "value": "cmdb_ci.os" },
      { "description": "mid.name", "label": "Mid => Name", "value": "mid.name" },
      { "description": "cmdb_ci.location", "label": "Host => Location", "value": "cmdb_ci.location" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.u_critical", "label": "Host => Critical", "value": "cmdb_ci.u_critical" },
      { "description": "cmdb_ci.model_id", "label": "Host => Model ID", "value": "cmdb_ci.model_id" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" },
      { "description": "cmdb_ci.manufacturer", "label": "Host => Manufacturer", "value": "cmdb_ci.manufacturer" },
      { "description": "cmdb_ci.owned_by", "label": "Host => Owned by", "value": "cmdb_ci.owned_by" },
      { "description": "cmdb_ci.asset_tag", "label": "Host => Asset tag", "value": "cmdb_ci.asset_tag" },
      { "description": "cmdb_ci.u_support_level", "label": "Host => Support Level", "value": "cmdb_ci.u_support_level" }
     ],
     "service": "$service",
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "mid.sys_id", "label": "Mid => Sys ID", "value": "mid.sys_id" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "2", "value": "2" },
      { "label": "$mid", "value": "$mid" },
      { "label": "$hostSearch", "value": "$hostSearch" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$supportGroup", "value": "$supportGroup" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "sysparam_query": "agent_extended_info.status!=2^mid.name=MID1_PROD_ATL0WSNWP022",
     "tableName": { "description": "sn_agent_ci_extended_info", "label": "Agent Client Collector Info", "value": "sn_agent_ci_extended_info" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ciClasses",
      "value": "$ciClasses"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the OS", "label": "OS", "value": "OS" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "service": "$service",
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "mid.sys_id", "label": "Mid => Sys ID", "value": "mid.sys_id" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "2", "value": "2" },
      { "label": "$mid", "value": "$mid" },
      { "label": "$hostSearch", "value": "$hostSearch" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$supportGroup", "value": "$supportGroup" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "sysparam_query": "agent_extended_info.status!=2^mid.name=MID1_PROD_ATL0WSNWP022",
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=Closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "HLA Log Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "total http 5xx",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "500",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    },
    {
     "title": "total errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "error",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-lightbulb-o\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# Open Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% CI Binding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci!=NULL^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% Anomalies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS^event_class=anomaly",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$nestedCIS^state=1",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "title": "% Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "incident!=NULL^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "state",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Top 10 Sources",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "source",
     "rowLimit": "10",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 8 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-comments-o\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Major Incidents</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# P1 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=1^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# P2 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=2^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 11 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-bullseye\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Clustering Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "group_source",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Alert Correlation Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "basicSysparm": [
      {
       "column": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "operator": { "description": "IN", "label": "is one of", "value": "IN" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "$nestedCIS", "value": "$nestedCIS" }
      },
      { "column": { "description": "state", "label": "State", "value": "state" }, "operator": { "description": "!=", "label": "is not", "value": "!=" }, "separator": { "label": "AND", "value": "^" }, "value": { "label": "Closed", "value": "Closed" } },
      {
       "column": { "description": "maintenance", "label": "Maintenance", "value": "maintenance" },
       "operator": { "description": "=", "label": "is", "value": "=" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "false", "value": "false" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
     "sortDirection": "ASC",
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "Closed", "value": "Closed" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "topology_child_depth": 3,
     "topology_parent_depth": 3,
     "trendPeriod": "1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-exclamation-triangle\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Alerts</span></span></span></a></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$cis", "value": "$cis" }
      },
      {
       "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$supportGroup", "value": "$supportGroup" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "cacheOverride": "5s",
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "3000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^cmdb_ciIN$nestedCIS"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
     "options": {
      "content": "<p><a><i class=\"fa fa-signal\" style=\"color: #84c9fb; font-size: 16pt;\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6; font-size: 16px;\">KPI Metric Baselines &nbsp;<span style=\"font-size: 10pt;\">*<em>select kpi metrics from '<strong>Metric KPI</strong>' filter</em></span></span></a></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
     "repeat": "metric",
     "targets": [
      {
       "basicSysparm": [
        {}
       ],
       "basic_sysparam": [
        {
         "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        { "label": "$metric", "value": "$metric" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "topology_child_depth": 3,
       "topology_parent_depth": 3
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
     "options": {
      "content": "<p><span style=\"font-size: 14pt;\">🗒&nbsp; <span style=\"font-size: 12pt; color: #eb459e;\"><em>Currently there is a limitation with the Grafana Plugin to show baselines for global metrics (not oned with resources - e.g. specific drive, interface, ...). Fix coming soon!&nbsp;</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
     "options": {
      "content": "<p><a><i class=\"fa fa-signal\" style=\"color: #84c9fb; font-size: 16pt;\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6; font-size: 16px;\">Metric Intelligence &nbsp;<span style=\"font-size: 10pt;\">*<em>select any metrics from '<strong>All Metrics</strong>' filter</em></span></span></a></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$allMetrics", "value": "$allMetrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-wrench\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Change Records - scope based on CI relationships</span></span></span></a></p>"
     }
    },
    {
     "title": "Change Records",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$nestedCIS", "value": "$nestedCIS" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "short_description", "value": "short_description" },
        { "description": "type", "label": "Type (String)", "value": "type" },
        { "label": "state", "value": "state" },
        { "description": "start_date", "label": "Planned start date (Date/Time)", "value": "start_date" },
        { "description": "end_date", "label": "Planned end date (Date/Time)", "value": "end_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "label": "active", "value": "active" },
        { "label": "escalation", "value": "escalation" },
        { "label": "urgency", "value": "urgency" },
        { "label": "impact", "value": "impact" }
       ],
       "sortDirection": "ASC",
       "tableName": { "description": "change_request", "label": "Change Request", "value": "change_request" },
       "topology_child_depth": 3,
       "topology_parent_depth": 3
      }
     ]
    }
   ]
  },
  {
   "title": "Software Installations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-list-ul\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Software on Server</span></span></span></a></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Software Installations",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "basicSysparm": [
        {
         "column": { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" },
         "operator": { "description": "=", "label": "is", "value": "=" },
         "separator": { "label": "AND", "value": "^" },
         "value": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_software_instance", "label": "Software Instance", "value": "cmdb_software_instance" },
       "topology_child_depth": 3,
       "topology_parent_depth": 3
      }
     ]
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-list-ul\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Running Processes on Server</span></span></span></a></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Running Processes",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "basicSysparm": [
        {
         "column": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "operator": { "description": "=", "label": "is", "value": "=" },
         "separator": { "label": "AND", "value": "^" },
         "value": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_running_process", "label": "Running Process", "value": "cmdb_running_process" },
       "topology_child_depth": 3,
       "topology_parent_depth": 3
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "nodeGraph",
     "gridPos": { "h": 15, "w": 13, "x": 0, "y": 42 },
     "targets": [
      {
       "basicSysparm": [
        {}
       ],
       "excludedClasses": [
        { "label": "$filterClasses", "value": "$filterClasses" }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "relationshipTypes": [
        { "label": "$relationshipType", "value": "$relationshipType" }
       ],
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Show relationships in the node graph panel",
        "label": "Node Graph",
        "value": "Node_Graph"
       },
       "selectedServiceList": { "label": "$ci", "value": "$ci" },
       "sortDirection": "ASC",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 14, "y": 42 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-tags\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Tags</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "title": "Tags",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 44 },
     "targets": [
      {
       "basicSysparm": [
        {
         "column": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "operator": { "label": "IN", "value": "IN" },
         "separator": { "label": "AND", "value": "^" },
         "value": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" },
       "topology_child_depth": 3,
       "topology_parent_depth": 3
      }
     ]
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-certificate\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">TLS Certificates</span></span></span></a></p>"
     }
    },
    {
     "title": "Expired Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^certificate_expiration_date<=javascript:gs.beginningOfToday()^cmdb_ciIN$ci^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Renewal Tasks",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" }
        },
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" }, "4": { "label": "AND", "value": "^" } },
        { "1": { "label": "cmdb_ci", "value": "cmdb_ci" }, "2": { "description": "IN", "label": "is one of", "value": "IN" }, "3": { "label": "$nestedCIS", "value": "$nestedCIS" }, "4": { "label": "AND", "value": "^" } }
       ],
       "cacheOverride": "5s",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "priority", "value": "priority" },
        { "label": "state", "value": "state" },
        { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
        { "label": "cmdb_ci", "value": "cmdb_ci" },
        { "label": "cmdb_ci.sys_id", "value": "cmdb_ci.sys_id" },
        { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" }
       ],
       "sortDirection": "ASC",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-list-alt\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">ACC Checks</span></span></span></a></p>"
     }
    },
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}