{
 "title": "ACC-L CI Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ci",
    "query": "507e0785dbcd3b4091e1db184b9619c1"
   },
   {
    "name": "kpis",
    "query": {}
   },
   {
    "name": "host",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   },
   {
    "name": "ip",
    "query": {}
   },
   {
    "name": "metrics",
    "query": {}
   },
   {
    "name": "anomalyCIS",
    "query": {}
   },
   {
    "name": "cpu_io_metric",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Summary for $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Linux",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "asset.display_name", "label": "Asset => Display name", "value": "asset.display_name" },
      { "description": "classification", "label": "Classification", "value": "classification" },
      { "description": "correlation_id", "label": "Correlation ID", "value": "correlation_id" },
      { "description": "cpu_core_count", "label": "CPU core count", "value": "cpu_core_count" },
      { "description": "cpu_name", "label": "CPU name", "value": "cpu_name" },
      { "description": "cpu_speed", "label": "CPU speed (MHz)", "value": "cpu_speed" },
      { "description": "default_gateway", "label": "Default Gateway", "value": "default_gateway" },
      { "description": "discovery_source", "label": "Discovery source", "value": "discovery_source" },
      { "description": "dns_domain", "label": "DNS Domain", "value": "dns_domain" },
      { "description": "disk_space", "label": "Disk space (GB)", "value": "disk_space" },
      { "description": "firewall_status", "label": "Firewall status", "value": "firewall_status" },
      { "description": "fqdn", "label": "Fully qualified domain name", "value": "fqdn" },
      { "description": "ip_address", "label": "IP Address", "value": "ip_address" },
      { "description": "kernel_release", "label": "Kernel Release", "value": "kernel_release" },
      { "description": "object_id", "label": "Object ID", "value": "object_id" },
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "os", "label": "Operating System", "value": "os" },
      { "description": "os_version", "label": "OS Version", "value": "os_version" },
      { "description": "ram", "label": "RAM (MB)", "value": "ram" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "virtual", "label": "Is Virtual", "value": "virtual" },
      { "description": "host_name", "label": "Host name", "value": "host_name" }
     ],
     "tableName": { "description": "cmdb_ci_linux_server", "label": "Linux Server", "value": "cmdb_ci_linux_server" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_class_name", "label": "Configuration Item => Class", "value": "ci_id.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_linux_server", "value": "cmdb_ci_linux_server" }
      },
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": { "label": "AND", "value": "^" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_class_name", "label": "Host => Class", "value": "cmdb_ci.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_linux_server", "value": "cmdb_ci_linux_server" }
      },
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "agent_version", "label": "Version", "value": "agent_version" }
     ],
     "tableName": { "description": "sn_agent_ci_extended_info", "label": "Agent Client Collector Info", "value": "sn_agent_ci_extended_info" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Golden Signals</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "# of Anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "state!=Closed^group_sourceIN6,5^source=Log Analytics^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    },
    {
     "basicSysparm": [
      {
       "column": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "operator": { "description": "IN", "label": "is one of", "value": "IN" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "sys_class_name", "label": "Class", "value": "sys_class_name" }
     ],
     "sortDirection": "ASC",
     "tableName": { "description": "cmdb_ci", "label": "Configuration Item", "value": "cmdb_ci" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "# of Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "rowLimit": "1",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "state!=Closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "Logs / Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "basicSysparm": [
      { "separator": { "label": "AND", "value": "^" } }
     ],
     "elasticSearch": "host: $host",
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
     "sortDirection": "ASC",
     "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3",
     "trendPeriod": "1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 9 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Sophie Anomaly Detection</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "$kpis",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 9 },
   "repeat": "kpis",
   "targets": [
    {
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "metricAnomaly": "true",
     "metricName": "$metric",
     "metricType": "*",
     "rowLimit": "2000",
     "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
     "selectedMetricNameList": [
      { "label": "$kpis", "value": "$kpis" }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
     "selectedSourceList": [
      { "label": "$ci", "value": "$ci" }
     ],
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "Surface Anomalies",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "basicSysparm": [
      {
       "column": { "description": "sn_extra_data.category", "label": "Extra data => Category", "value": "sn_extra_data.category" },
       "operator": { "description": "=", "label": "is", "value": "=" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "2", "value": "2" }
      },
      {
       "column": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "operator": { "description": "IN", "label": "is one of", "value": "IN" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "$ci", "value": "$ci" }
      },
      { "column": { "description": "state", "label": "State", "value": "state" }, "operator": { "description": "!=", "label": "is not", "value": "!=" }, "separator": { "label": "AND", "value": "^" }, "value": { "label": "Closed", "value": "Closed" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "number", "label": "Number", "value": "number" },
      { "description": "sn_extra_data.explanation", "label": "Extra data => Explanation", "value": "sn_extra_data.explanation" },
      { "description": "sn_extra_data.anomaly", "label": "Extra data => Anomaly", "value": "sn_extra_data.anomaly" }
     ],
     "sortDirection": "ASC",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    },
    {
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alerts", "label": "Alerts", "value": "Alerts" },
     "sortDirection": "ASC",
     "sysparam_query": "sn_extra_data.category=2^cmdb_ciIN$ci",
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 22 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Active Alerts</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$cis", "value": "$cis" }
        },
        {
         "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$supportGroup", "value": "$supportGroup" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_class_name=cmdb_ci_linux_server^cmdb_ci=$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "Log Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 22, "x": 0, "y": 23 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Log KPIs</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "http 5xx",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "host: $host AND (raw_message: 500 OR raw_message: 503 OR raw_message: 505 OR raw_message: 511)",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    },
    {
     "title": "errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "host: $host AND raw_message: error",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    }
   ]
  },
  {
   "title": "Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 22, "x": 0, "y": 24 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Recent Changes</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Changes (last 7 days)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basicSysparm": [
        {
         "column": { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" },
         "operator": { "description": "=", "label": "is", "value": "=" },
         "value": { "label": "cmdb_ci_linux_server", "value": "cmdb_ci_linux_server" }
        },
        {
         "column": { "label": "sys_created_on", "value": "sys_created_on" },
         "operator": { "description": ">=", "label": "greater than or is", "value": ">=" },
         "separator": { "label": "AND", "value": "^" },
         "value": {
          "label": "javascript:gs.beginningOfLast7Days()",
          "value": "javascript:gs.beginningOfLast7Days()"
         }
        },
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "description": "=", "label": "is", "value": "=" }, "separator": { "label": "AND", "value": "^" }, "value": { "label": "$ci", "value": "$ci" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "tableName": { "description": "change_request", "label": "Change Request", "value": "change_request" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$metrics",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "repeat": "metrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$metrics", "value": "$metrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Software Installations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 26 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Software on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_software_instance", "label": "Software Instance", "value": "cmdb_software_instance" }
      }
     ]
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 27 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Running Processes on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_running_process", "label": "Running Process", "value": "cmdb_running_process" }
      }
     ]
    }
   ]
  }
 ]
}