{
 "title": "Application Service Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application Service",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "Available Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "namespaces" },
   {
    "name": "filterClasses",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" }
      }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "sortBy": { "description": "name", "label": "Name", "value": "name" },
     "sysparam_option1": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "busines_criticality", "label": "Business criticality", "value": "busines_criticality" },
      { "description": "severity", "label": "Severity", "value": "severity" },
      { "description": "type", "label": "Service Type", "value": "type" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "u_business_segment.sys_id", "label": "Business Segment => Sys ID", "value": "u_business_segment.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" },
      { "label": "is one of", "value": "IN" },
      { "label": "is one of", "value": "IN" },
      { "label": "is one of", "value": "IN" },
      { "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "$service", "value": "$service" },
      { "label": "$business_criticality", "value": "$business_criticality" },
      { "label": "$severity", "value": "$severity" },
      { "label": "$type", "value": "$type" },
      { "label": "$nameSearch", "value": "$nameSearch" },
      { "label": "$businessSegment", "value": "$businessSegment" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_ci_service_discovered", "label": "Mapped Application Service", "value": "cmdb_ci_service_discovered" }
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 4 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" }
      }
     ],
     "selectedQueryCategory": {
      "description": "Gathers business service status over the last 90 days",
      "label": "Outage Status",
      "value": "Outage_Status"
     },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Topology - <span style=\"font-size: 12pt; color: #eb459e;\">🏅 <em>click on the 'Child' and 'Parent' Topo Levels filters to expand view, also filter specific Relationship and CI Class!</em></span> &nbsp;</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" }
      }
     ],
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "sysparam_query": "tionshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
     "topology_child_depth": "$childTopo",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "description": "configuration_item.sys_class_name",
       "label": "Configuration item => Class",
       "value": "configuration_item.sys_class_name"
      },
      { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
      { "description": "key", "label": "Key", "value": "key" },
      { "description": "value", "label": "Value", "value": "value" }
     ],
     "sysparam_option1": [
      { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "# Open Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sysparam_query": "state!=closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% CI Binding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sysparam_query": "cmdb_ci!=NULL^maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sysparam_query": "maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$ci^state=1",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "title": "% Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sysparam_query": "incident!=NULL^maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "state",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sysparam_query": "maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "group_source",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Impacted App Svcs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "al_sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "stat_business_service",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "al_maintenance=false^al_state!=Closed^al_cmdb_ciIN$ci",
     "tableName": { "label": "em_alert_bs_status_view", "value": "em_alert_bs_status_view" }
    }
   ]
  },
  {
   "title": "# P1 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=1^maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# P2 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=2^maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 29 },
   "options": {
    "content": "<p style=\"text-align: left;\"><span style=\"font-size: 14pt;\"><img src=$image width=\"27\" height=\"27\" alt=\"\" style=\"float: left;\" />&nbsp; Active Alerts <span style=\"font-size: 12pt; color: #eb459e;\">🏅<em>click on the 'group' link to drill into correlation insights!</em></span></span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Alert Correlation Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      { "1": { "description": "state", "label": "State", "value": "state" }, "2": { "description": "!=", "label": "is not", "value": "!=" }, "3": { "label": "Closed", "value": "Closed" }, "4": { "label": "AND", "value": "^" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
     "sortDirection": "ASC",
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "Closed", "value": "Closed" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "trendPeriod": "1"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$cis", "value": "$cis" }
      },
      {
       "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$supportGroup", "value": "$supportGroup" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "3000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$ci"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 4 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Metric Intelligence&nbsp; <span style=\"font-size: 10pt;\">*<em>select any metrics from '<strong>All Metrics</strong>' filter</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 33 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Change Records - scope based on CI relationships&nbsp; </span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$ci"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Insights Last 30 Days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 8 },
     "options": {
      "content": "<p style=\"text-align: left;\"><span style=\"font-size: 14pt;\"><img src=$image width=\"27\" height=\"27\" alt=\"\" style=\"float: left;\" />&nbsp; Overall <span style=\"color: #f1c40f;\">Noise Reduction</span> Last 30 days</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ciIN$ci",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^certificate_expiration_date<=javascript:gs.beginningOfToday()^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Renewal Tasks",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" }
        },
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" }, "4": { "label": "AND", "value": "^" } },
        { "1": { "label": "cmdb_ci", "value": "cmdb_ci" }, "2": { "description": "IN", "label": "is one of", "value": "IN" }, "3": { "label": "$ci", "value": "$ci" }, "4": { "label": "AND", "value": "^" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "priority", "value": "priority" },
        { "label": "state", "value": "state" },
        { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
        { "label": "cmdb_ci", "value": "cmdb_ci" },
        { "label": "cmdb_ci.sys_id", "value": "cmdb_ci.sys_id" },
        { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
        { "description": "root_issuer", "label": "Root issuer", "value": "root_issuer" },
        { "label": "cmdb_ci.subject_organization", "value": "cmdb_ci.subject_organization" },
        { "label": "cmdb_ci.is_self_signed", "value": "cmdb_ci.is_self_signed" }
       ],
       "sortDirection": "ASC",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}