{
 "title": "Application Service 360 Degree View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Application Service",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "Available Metrics",
    "query": {}
   },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "namespaces" },
   {
    "name": "filterClasses",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   },
   {
    "name": "group",
    "label": "Alert Group",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Application Service details:   $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 1 },
   "options": {
    "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-vcard\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">CI Attributes</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" }
      }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "sortBy": { "description": "name", "label": "Name", "value": "name" },
     "sysparam_option1": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "busines_criticality", "label": "Business criticality", "value": "busines_criticality" },
      { "description": "severity", "label": "Severity", "value": "severity" },
      { "description": "type", "label": "Service Type", "value": "type" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "u_business_segment.sys_id", "label": "Business Segment => Sys ID", "value": "u_business_segment.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" },
      { "label": "is one of", "value": "IN" },
      { "label": "is one of", "value": "IN" },
      { "label": "is one of", "value": "IN" },
      { "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "$service", "value": "$service" },
      { "label": "$business_criticality", "value": "$business_criticality" },
      { "label": "$severity", "value": "$severity" },
      { "label": "$type", "value": "$type" },
      { "label": "$nameSearch", "value": "$nameSearch" },
      { "label": "$businessSegment", "value": "$businessSegment" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_ci_service_discovered", "label": "Mapped Application Service", "value": "cmdb_ci_service_discovered" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 6 },
   "options": {
    "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 14pt;\"><i class=\"fa fa-medkit\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Outage Report</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$service", "value": "$service" }
      }
     ],
     "selectedQueryCategory": {
      "description": "Gathers business service status over the last 90 days",
      "label": "Outage Status",
      "value": "Outage_Status"
     },
     "selectedServiceList": { "label": "$service", "value": "$service" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "options": {
    "content": "\n<p><a><span style=\"color: #57F287;\"><span style=\"font-size: 14pt;\"><i class=\"fa fa-square\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Available</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "options": {
    "content": "\n<p><a><span style=\"color: #ED4245;\"><span style=\"font-size: 14pt;\"><i class=\"fa fa-square\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Outage</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Topology and Tags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-connectdevelop\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Topology</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 8, "x": 13, "y": 13 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-tags\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Tags</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "type": "nodeGraph",
     "gridPos": { "h": 13, "w": 13, "x": 0, "y": 15 },
     "targets": [
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$ci", "value": "$ci" } }
       ],
       "excludedClasses": [
        { "label": "$filterClasses", "value": "$filterClasses" }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "relationshipTypes": [
        { "label": "$relationshipType", "value": "$relationshipType" }
       ],
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Show relationships in the node graph panel",
        "label": "Node Graph",
        "value": "Node_Graph"
       },
       "selectedServiceList": { "label": "$service", "value": "$service" },
       "sortDirection": "ASC",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    },
    {
     "title": "Tags",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 13, "y": 15 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "9999",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        {
         "description": "configuration_item.sys_class_name",
         "label": "Configuration item => Class",
         "value": "configuration_item.sys_class_name"
        },
        { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
        { "description": "key", "label": "Key", "value": "key" },
        { "description": "value", "label": "Value", "value": "value" }
       ],
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
      }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-lightbulb-o\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# Open Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% CI Binding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci!=NULL^maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% Anomalies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group^event_class=anomaly",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$ci^state=1",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "title": "% Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "incident!=NULL^maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "state",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=Closed^cmdb_ciIN$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Top 10 Sources",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "source",
     "rowLimit": "10",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 14 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-comments-o\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Major Incidents</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# P1 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=1^maintenance=false^state!=Closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# P2 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=2^maintenance=false^state!=Closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 17 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-bullseye\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Clustering Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "group_source",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$ci^group_sourceIN$group",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Alert Correlation Timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      { "1": { "description": "state", "label": "State", "value": "state" }, "2": { "description": "!=", "label": "is not", "value": "!=" }, "3": { "label": "Closed", "value": "Closed" }, "4": { "label": "AND", "value": "^" } },
      {
       "1": { "description": "group_source", "label": "Group", "value": "group_source" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$group", "value": "$group" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": {
      "description": "Get timeseries data based on a time trend",
      "label": "Trend Data",
      "value": "Trend_Data"
     },
     "selectedTrendBy": { "label": "Minute", "value": "minute" },
     "selectedTrendColumn": { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
     "sortDirection": "ASC",
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "Closed", "value": "Closed" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" },
     "trendPeriod": "1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 24 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-exclamation-triangle\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Alerts</span></span></span></a></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$cis", "value": "$cis" }
      },
      {
       "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$supportGroup", "value": "$supportGroup" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "cacheOverride": "5s",
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "3000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$ci^group_sourceIN$group"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-battery-three-quarters\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Resources</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$allMetrics", "value": "$allMetrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 58 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-wrench\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Related Changes or Deployments (CI/CD)</span></span></span></a></p>"
     }
    },
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$ci", "value": "$ci" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "tableName": { "description": "change_request", "label": "Change Request", "value": "change_request" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    }
   ]
  },
  {
   "title": "Alert Insights Last 30 Days",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 59 },
     "options": {
      "content": "<p style=\"text-align: left;\"><span style=\"font-size: 14pt;\"><img src=$image width=\"27\" height=\"27\" alt=\"\" style=\"float: left;\" />&nbsp; Overall <span style=\"color: #f1c40f;\">Noise Reduction</span> Last 30 days</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ciIN$ci",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$ci",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 60 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-cloud\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Cloud Events</span></span></span></a></p>"
     }
    },
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 53 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-certificate\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">TLS Certificates</span></span></span></a></p>"
     }
    },
    {
     "title": "Expired Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^certificate_expiration_date<=javascript:gs.beginningOfToday()^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$ci",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Renewal Tasks",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" }
        },
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" }, "4": { "label": "AND", "value": "^" } },
        { "1": { "label": "cmdb_ci", "value": "cmdb_ci" }, "2": { "description": "IN", "label": "is one of", "value": "IN" }, "3": { "label": "$ci", "value": "$ci" }, "4": { "label": "AND", "value": "^" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "priority", "value": "priority" },
        { "label": "state", "value": "state" },
        { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
        { "label": "cmdb_ci", "value": "cmdb_ci" },
        { "label": "cmdb_ci.sys_id", "value": "cmdb_ci.sys_id" },
        { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
        { "description": "root_issuer", "label": "Root issuer", "value": "root_issuer" },
        { "label": "cmdb_ci.subject_organization", "value": "cmdb_ci.subject_organization" },
        { "label": "cmdb_ci.is_self_signed", "value": "cmdb_ci.is_self_signed" }
       ],
       "sortDirection": "ASC",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 51 },
     "options": {
      "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-list-alt\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">ACC Checks</span></span></span></a></p>"
     }
    },
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}