{
 "title": "AWS CI Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "label": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "label": "ci",
    "query": "d8a41e411b23a4107ef18736604bcb1b"
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      { "1": { "label": "vm_sys_id", "value": "vm_sys_id" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "$ci", "value": "$ci" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "label": "vm_last_discovered", "value": "vm_last_discovered" },
      { "label": "ldc_name", "value": "ldc_name" },
      { "label": "ldc_object_id", "value": "ldc_object_id" },
      { "label": "ldc_region", "value": "ldc_region" },
      { "label": "vm_cpus", "value": "vm_cpus" },
      { "label": "vm_disks", "value": "vm_disks" },
      { "label": "vm_disks_size", "value": "vm_disks_size" },
      { "label": "vm_guest_os_fullname", "value": "vm_guest_os_fullname" },
      { "label": "vm_ip_address", "value": "vm_ip_address" },
      { "label": "vm_memory", "value": "vm_memory" },
      { "label": "vm_monitor", "value": "vm_monitor" },
      { "label": "vm_name", "value": "vm_name" },
      { "label": "vm_nics", "value": "vm_nics" },
      { "label": "vm_object_id", "value": "vm_object_id" },
      { "label": "vm_state", "value": "vm_state" },
      { "label": "vm_sys_id", "value": "vm_sys_id" },
      { "label": "vm_terminated_on", "value": "vm_terminated_on" },
      { "label": "vm_vm_inst_id", "value": "vm_vm_inst_id" },
      { "label": "vm_sys_class_name", "value": "vm_sys_class_name" }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "label": "vm_state", "value": "vm_state" },
      { "label": "ldc_region", "value": "ldc_region" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" },
      { "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$region", "value": "$region" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "label": "sn_itom_pattern_amazon_vm_instance",
      "value": "sn_itom_pattern_amazon_vm_instance"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "parent.sys_id", "label": "Parent => Sys ID", "value": "parent.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": { "description": "child.sys_class_name", "label": "Child => Class", "value": "child.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_os_template", "value": "cmdb_ci_os_template" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "parent.sys_id", "label": "Parent => Sys ID", "value": "parent.sys_id" },
      { "description": "child.name", "label": "Child => Name", "value": "child.name" }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "label": "vm_state", "value": "vm_state" },
      { "label": "ldc_region", "value": "ldc_region" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" },
      { "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$region", "value": "$region" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_rel_ci", "label": "CI Relationship", "value": "cmdb_rel_ci" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "rowLimit": "1",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": { "label": "$ci", "value": "$ci" },
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses",
     "topology_child_depth": "$childTopo",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "description": "configuration_item.sys_class_name",
       "label": "Configuration item => Class",
       "value": "configuration_item.sys_class_name"
      },
      { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
      { "description": "key", "label": "Key", "value": "key" },
      { "description": "value", "label": "Value", "value": "value" }
     ],
     "sysparam_option1": [
      { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 53 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        {
         "__isNew__": true,
         "label": "$metric",
         "value": "$metric"
        }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}