{
 "title": "Azure CI 360 Degree View",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "label": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "label": "ci",
    "query": "6ecdc24d876f2010cecc87f7cebb3590"
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" }
    }
   ]
  },
  {
   "title": "Quick Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quick Links",
     "type": "text",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 3 },
     "options": {
      "content": "<div class=\"mcd-container\"><nav>\n<ul class=\"mcd-menu\">\n  <li><strong></strong></li>\n<li><a> <i class=\"fa fa-lightbulb-o\"></i> <strong>ITOM Insights</strong> <small></small></a></li>\n<li><a href=\"https://github.com/optimizca/servicenow-grafana\" rel=\"noopener noreferrer\" target=\"_blank\"> <i class=\"fa fa-github-square\"></i> <strong>GitHub</strong> <small></small></a></li>\n<li><a> <i class=\"fa fa-wpexplorer\"></i> <strong>AIOps</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/v_aus7Z7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-exclamation-triangle\"></i>Event Mgmt</a></li>\n<li><a href=\"/d/rD_AfGznz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-sitemap\"></i>Application Services</a></li>\n<li><a href=\"/d/FUyeXrn7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-search-plus\"></i>Log Analytics Viewer</a></li>\n<li><a href=\"/d/ReZU-Onnk\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tachometer\"></i>Observability</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-cloud\"></i><strong>Cloud</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/CMBbLUi7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-amazon\"></i>AWS EC2</a></li>\n<li><a href=\"/d/s88Ssjmnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-bolt\"></i>AWS Lambda</a></li>\n<li><a href=\"/d/bJCxbfW7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-windows\"></i>Azure VMs</a></li>\n<li><a href=\"/d/y1rzi9W7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tags\"></i>Tag Health</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-map-o\"></i><strong>Discovery</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/Onij2tR7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-th-list\"></i>ACC Agent Inventory</a></li>\n<li><a href=\"/d/P29OUYS7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-files-o\"></i>Compare CIs</a></li>\n<li><a href=\"/d/DDjMy8Knz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-linux\"></i>Linux Servers</a></li>\n<li><a href=\"#\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-windows\"></i>Windows Servers</a></li>\n<li><a href=\"/d/hBYzNBT7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-certificate\"></i>TLS Certificates</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-cubes\"></i><strong>Kubernetes</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/lAoEVhD7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa  fa-home\"></i>CNO Home</a></li>\n<li><a href=\"/d/t_qus7Z7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-exclamation-triangle\"></i>CNO Event Mgmt</a></li>\n<li><a href=\"/d/17U4IvAnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-spinner\"></i>K8s Cluster 360 view</a></li>\n<li><a href=\"/d/17U7IvAnq\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-server\"></i>K8s Node 360 view</a></li>\n<li><a href=\"/d/H-YoYgWnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-bar-chart-o\"></i>K8s dashboard</a></li>\n<li><a href=\"/d/ReZU-Onnk\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-eye\"></i>Observability</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-shopping-bag\"></i><strong>Services</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/rD_AfGznz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-sitemap\"></i>Application Services</a></li>\n<li><a href=\"/d/8koJ9VVnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-medkit\"></i>Outage Report</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-server\"></i><strong>Virtual Infra</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/bJCxbfW7x\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-power-off\"></i>vCenter Inventory</a></li>\n<li><a href=\"/d/y1rzi9W7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tags\"></i>Tag Health</a></li>\n</ul>\n</li>\n</ul>\n</nav></div>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    }
   ]
  },
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "basic_sysparam": [
      { "1": { "label": "vm_sys_id", "value": "vm_sys_id" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "$ci", "value": "$ci" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "label": "vm_last_discovered", "value": "vm_last_discovered" },
      { "label": "ldc_name", "value": "ldc_name" },
      { "label": "ldb_object_id", "value": "ldb_object_id" },
      { "label": "ldc_region", "value": "ldc_region" },
      { "label": "vm_cpus", "value": "vm_cpus" },
      { "label": "vm_disks", "value": "vm_disks" },
      { "label": "vm_disks_size", "value": "vm_disks_size" },
      { "label": "vm_guest_of_fullname", "value": "vm_guest_of_fullname" },
      { "label": "vm_ip_address", "value": "vm_ip_address" },
      { "label": "vm_memory", "value": "vm_memory" },
      { "label": "vm_monitor", "value": "vm_monitor" },
      { "label": "vm_name", "value": "vm_name" },
      { "label": "vm_nics", "value": "vm_nics" },
      { "label": "vm_object_id", "value": "vm_object_id" },
      { "label": "vm_state", "value": "vm_state" },
      { "label": "vm_sys_id", "value": "vm_sys_id" },
      { "label": "vm_terminated_on", "value": "vm_terminated_on" },
      { "label": "vm_vm_inst_id", "value": "vm_vm_inst_id" },
      { "label": "vm_sys_class_name", "value": "vm_sys_class_name" },
      { "label": "vm_model_id", "value": "vm_model_id" },
      { "label": "vm_u_used_for", "value": "vm_u_used_for" }
     ],
     "sysparam_count": 2,
     "sysparam_option1": [
      { "label": "vm_state", "value": "vm_state" },
      { "label": "ldc_region", "value": "ldc_region" },
      { "label": "vm_name", "value": "vm_name" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$region", "value": "$region" },
      { "label": "$nameSearch", "value": "$nameSearch" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "label": "sn_itom_pattern_azure_virtual_machine_instance",
      "value": "sn_itom_pattern_azure_virtual_machine_instance"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "sysparam_count": 2,
     "sysparam_option1": [
      { "label": "vm_state", "value": "vm_state" },
      { "label": "ldc_region", "value": "ldc_region" },
      { "label": "vm_name", "value": "vm_name" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$region", "value": "$region" },
      { "label": "$nameSearch", "value": "$nameSearch" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "parent.sys_id", "label": "Parent => Sys ID", "value": "parent.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": { "description": "child.sys_class_name", "label": "Child => Class", "value": "child.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_os_template", "value": "cmdb_ci_os_template" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "parent.sys_id", "label": "Parent => Sys ID", "value": "parent.sys_id" },
      { "description": "child.name", "label": "Child => Name", "value": "child.name" }
     ],
     "sysparam_count": 2,
     "sysparam_option1": [
      { "label": "vm_state", "value": "vm_state" },
      { "label": "ldc_region", "value": "ldc_region" },
      { "label": "vm_name", "value": "vm_name" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$region", "value": "$region" },
      { "label": "$nameSearch", "value": "$nameSearch" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_rel_ci", "label": "CI Relationship", "value": "cmdb_rel_ci" }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {
       "1": { "description": "element_id.sys_class_name", "label": "Element Identifier => Class", "value": "element_id.sys_class_name" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "cmdb_ci_vm_instance", "value": "cmdb_ci_vm_instance" }
      },
      {
       "1": { "description": "vt_end", "label": "Valid Time End", "value": "vt_end" },
       "2": { "description": ">=", "label": "greater than or is", "value": ">=" },
       "3": {
        "label": "javascript:gs.beginningOfCurrentMinute()",
        "value": "javascript:gs.beginningOfCurrentMinute()"
       },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "rowLimit": "1",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "selectedtableColumns": [
      { "description": "element_id.sys_id", "label": "Element Identifier => Sys ID", "value": "element_id.sys_id" },
      { "description": "severity", "label": "Severity", "value": "severity" }
     ],
     "sysparam_query": "state!=closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  { "title": "Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "novatec-sdg-panel",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
     "selectedServiceList": { "label": "$ci", "value": "$ci" },
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses",
     "topology_child_depth": "$childTopo",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "description": "configuration_item.sys_class_name",
       "label": "Configuration item => Class",
       "value": "configuration_item.sys_class_name"
      },
      { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
      { "description": "key", "label": "Key", "value": "key" },
      { "description": "value", "label": "Value", "value": "value" }
     ],
     "sysparam_option1": [
      { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 28 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        {
         "__isNew__": true,
         "label": "$metric",
         "value": "$metric"
        }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}