{
 "title": "CI Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "Metric KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "label": "All Metrics",
    "query": {}
   },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   { "name": "namespaces" },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "metric_type",
    "query": {}
   },
   { "name": "parentTopo", "label": "Parent Topo Levels", "query": "0,1,2,3,4,5" },
   { "name": "childTopo", "label": "Child Topo Levels", "query": "0,1,2,3,4,5" },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "nestedVMS",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">ACC-M Agent&nbsp;</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ciClasses",
      "value": "$ciClasses"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the OS", "label": "OS", "value": "OS" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
      { "description": "cmdb_ci.sys_class_name", "label": "Host => Class", "value": "cmdb_ci.sys_class_name" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "running_checks_num", "label": "Number of running checks", "value": "running_checks_num" },
      { "description": "data_collection", "label": "Data Collection", "value": "data_collection" },
      { "description": "agent_version", "label": "Version", "value": "agent_version" },
      { "description": "ip_address", "label": "IP address", "value": "ip_address" },
      { "description": "cmdb_ci.last_discovered", "label": "Host => Most recent discovery", "value": "cmdb_ci.last_discovered" },
      {
       "description": "cmdb_ci.fqdn",
       "label": "Host => Fully qualified domain name",
       "value": "cmdb_ci.fqdn"
      },
      { "label": "cmdb_ci.os", "value": "cmdb_ci.os" },
      { "description": "mid.name", "label": "Mid => Name", "value": "mid.name" },
      { "description": "cmdb_ci.location", "label": "Host => Location", "value": "cmdb_ci.location" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.u_critical", "label": "Host => Critical", "value": "cmdb_ci.u_critical" },
      { "description": "cmdb_ci.model_id", "label": "Host => Model ID", "value": "cmdb_ci.model_id" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" },
      { "description": "cmdb_ci.manufacturer", "label": "Host => Manufacturer", "value": "cmdb_ci.manufacturer" },
      { "description": "cmdb_ci.owned_by", "label": "Host => Owned by", "value": "cmdb_ci.owned_by" },
      { "description": "cmdb_ci.asset_tag", "label": "Host => Asset tag", "value": "cmdb_ci.asset_tag" },
      { "description": "cmdb_ci.u_support_level", "label": "Host => Support Level", "value": "cmdb_ci.u_support_level" }
     ],
     "service": "$service",
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "mid.sys_id", "label": "Mid => Sys ID", "value": "mid.sys_id" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "2", "value": "2" },
      { "label": "$mid", "value": "$mid" },
      { "label": "$hostSearch", "value": "$hostSearch" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$supportGroup", "value": "$supportGroup" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "sysparam_query": "agent_extended_info.status!=2^mid.name=MID1_PROD_ATL0WSNWP022",
     "tableName": { "description": "sn_agent_ci_extended_info", "label": "Agent Client Collector Info", "value": "sn_agent_ci_extended_info" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "/cpu|memory/",
     "metricType": "*",
     "selectedAgentFilter": {
      "__isNew__": true,
      "label": "$ciClasses",
      "value": "$ciClasses"
     },
     "selectedAgentFilterType": { "description": "Get all agents matching the OS", "label": "OS", "value": "OS" },
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "service": "$service",
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "status", "label": "Status", "value": "status" },
      { "description": "mid.sys_id", "label": "Mid => Sys ID", "value": "mid.sys_id" },
      { "description": "cmdb_ci.name", "label": "Host => Name", "value": "cmdb_ci.name" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.environment", "label": "Host => Environment", "value": "cmdb_ci.environment" },
      { "description": "cmdb_ci.support_group", "label": "Host => Support group", "value": "cmdb_ci.support_group" }
     ],
     "sysparam_option2": [
      { "description": "!=", "label": "is not", "value": "!=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "LIKE", "label": "contains", "value": "LIKE" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "2", "value": "2" },
      { "label": "$mid", "value": "$mid" },
      { "label": "$hostSearch", "value": "$hostSearch" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$usedFor", "value": "$usedFor" },
      { "label": "$supportGroup", "value": "$supportGroup" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "sysparam_query": "agent_extended_info.status!=2^mid.name=MID1_PROD_ATL0WSNWP022",
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=Closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "HLA Log Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "total http 5xx",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "500",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    },
    {
     "title": "total errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "elasticSearch": "error",
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Get timeseries data based on a time trend",
        "label": "Trend Data",
        "value": "Trend_Data"
       },
       "selectedTrendBy": { "label": "Minute", "value": "minute" },
       "selectedTrendColumn": { "description": "time", "label": "Time", "value": "time" },
       "tableName": { "description": "sn_occ_log_viewer_parent", "label": "Log Viewer Parent", "value": "sn_occ_log_viewer_parent" },
       "trendPeriod": "1"
      }
     ]
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 8 },
   "options": {
    "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">ITOM Alerts&nbsp;</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 10 },
   "options": {
    "content": "<p style=\"text-align: center;\"><span style=\"font-size: 14pt;\">Overall Noise Reduction Last 30 days</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 10, "y": 10 },
   "options": {
    "content": "<p style=\"text-align: center;\"><span style=\"font-size: 14pt;\">Alert Insights</span></p>"
   },
   "targets": [
    {
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "event_count",
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "groupBy": "state",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAggregateType": { "label": "SUM", "value": "SUM" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Incidents Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 11, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "panelId": 81,
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAlertStateList": {
      "description": "Get All alerts Open,Reopen, and Closed",
      "label": "All",
      "value": "All"
     },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS"
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 26 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">KPI Metric Baselines &nbsp;<span style=\"font-size: 10pt;\">*<em>select kpi metrics from '<strong>Metric KPI</strong>' filter</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
     "repeat": "metric",
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "cmdb_ci.sys_id", "label": "Host => Sys ID", "value": "cmdb_ci.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": { "label": "$metric", "value": "$metric" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 33 },
     "options": {
      "content": "<p><span style=\"font-size: 14pt;\">🗒&nbsp; <span style=\"font-size: 12pt; color: #eb459e;\"><em>Currently there is a limitation with the Grafana Plugin to show baselines for global metrics (not oned with resources - e.g. specific drive, interface, ...). Fix coming soon!&nbsp;</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 35 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Metric Intelligence&nbsp; <span style=\"font-size: 10pt;\">*<em>select any metrics from '<strong>All Metrics</strong>' filter</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recent Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 30 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Change Records - scope based on CI relationships&nbsp; </span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Change Records",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Software Installations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 12 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Software on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Software Installations",
     "type": "table",
     "gridPos": { "h": 14, "w": 17, "x": 0, "y": 14 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "installed_on.sys_id", "label": "Installed on => Sys ID", "value": "installed_on.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_sam_sw_install", "label": "Software Installation", "value": "cmdb_sam_sw_install" }
      }
     ]
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 29 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Running Processes on Server<span style=\"font-size: 10pt;\"></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Running Processes",
     "type": "table",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "=", "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_running_process", "label": "Running Process", "value": "cmdb_running_process" }
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">Topology&nbsp; <span style=\"font-size: 10pt;\">*<em>select <strong>child</strong> and <strong>parent</strong> topo levels to widen topology view</em></span></span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "type": "novatec-sdg-panel",
     "gridPos": { "h": 15, "w": 14, "x": 0, "y": 33 },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
       "selectedServiceList": { "label": "$ci", "value": "$ci" },
       "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    },
    {
     "title": "Tags",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 14, "y": 33 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$nestedVMS", "value": "$nestedVMS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 31 },
     "options": {
      "content": "<p><img src=$image width=\"50\" height=\"50\" alt=\"\" />&nbsp; &nbsp;<span style=\"font-size: 14pt;\">ACC-M Checks&nbsp;</span></p>"
     },
     "targets": [
      {
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "computer.sys_id", "label": "Computer => Sys ID", "value": "computer.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}