{
 "title": "Generic CI 360 Degree View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   { "name": "namespaces" },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" }
    }
   ]
  },
  {
   "title": "Quick Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quick Links",
     "type": "text",
     "gridPos": { "h": 7, "w": 13, "x": 0, "y": 3 },
     "options": {
      "content": "<div class=\"mcd-container\"><nav>\n<ul class=\"mcd-menu\">\n  <li><strong></strong></li>\n<li><a> <i class=\"fa fa-lightbulb-o\"></i> <strong>ITOM Insights</strong> <small></small></a></li>\n<li><a href=\"https://github.com/optimizca/servicenow-grafana\" rel=\"noopener noreferrer\" target=\"_blank\"> <i class=\"fa fa-github-square\"></i> <strong>GitHub</strong> <small></small></a></li>\n<li><a> <i class=\"fa fa-wpexplorer\"></i> <strong>AIOps</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/v_aus7Z7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-exclamation-triangle\"></i>Event Mgmt</a></li>\n<li><a href=\"/d/rD_AfGznz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-sitemap\"></i>Application Services</a></li>\n<li><a href=\"/d/FUyeXrn7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-search-plus\"></i>Log Analytics Viewer</a></li>\n<li><a href=\"/d/ReZU-Onnk\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tachometer\"></i>Observability</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-cloud\"></i><strong>Cloud</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/CMBbLUi7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-amazon\"></i>AWS EC2</a></li>\n<li><a href=\"/d/s88Ssjmnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-bolt\"></i>AWS Lambda</a></li>\n<li><a href=\"/d/bJCxbfW7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-windows\"></i>Azure VMs</a></li>\n<li><a href=\"/d/y1rzi9W7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tags\"></i>Tag Health</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-map-o\"></i><strong>Discovery</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/Onij2tR7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-th-list\"></i>ACC Agent Inventory</a></li>\n<li><a href=\"/d/P29OUYS7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-files-o\"></i>Compare CIs</a></li>\n<li><a href=\"/d/DDjMy8Knz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-linux\"></i>Linux Servers</a></li>\n<li><a href=\"#\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-windows\"></i>Windows Servers</a></li>\n<li><a href=\"/d/hBYzNBT7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-certificate\"></i>TLS Certificates</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-cubes\"></i><strong>Kubernetes</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/lAoEVhD7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa  fa-home\"></i>CNO Home</a></li>\n<li><a href=\"/d/t_qus7Z7z\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-exclamation-triangle\"></i>CNO Event Mgmt</a></li>\n<li><a href=\"/d/17U4IvAnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-spinner\"></i>K8s Cluster 360 view</a></li>\n<li><a href=\"/d/17U7IvAnq\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-server\"></i>K8s Node 360 view</a></li>\n<li><a href=\"/d/H-YoYgWnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-bar-chart-o\"></i>K8s dashboard</a></li>\n<li><a href=\"/d/ReZU-Onnk\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-eye\"></i>Observability</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-shopping-bag\"></i><strong>Services</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/rD_AfGznz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-sitemap\"></i>Application Services</a></li>\n<li><a href=\"/d/8koJ9VVnz\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-medkit\"></i>Outage Report</a></li>\n</ul>\n</li>\n<li><a><i class=\"fa fa-server\"></i><strong>Virtual Infra</strong>&nbsp;<small></small></a>\n<ul>\n<li><a href=\"/d/bJCxbfW7x\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-power-off\"></i>vCenter Inventory</a></li>\n<li><a href=\"/d/y1rzi9W7k\" rel=\"noopener noreferrer\" target=\"_blank\"><i class=\"fa fa-tags\"></i>Tag Health</a></li>\n</ul>\n</li>\n</ul>\n</nav></div>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    }
   ]
  },
  {
   "title": "$ci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 4 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-vcard\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">CI Attributes</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "title": "Attributes",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "1",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_ci", "label": "Configuration Item", "value": "cmdb_ci" }
      },
      {
       "aggregateColumn": "severity",
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "groupBy": "cmdb_ci.sys_id",
       "rowLimit": "9999",
       "selectedAggregateType": { "label": "MIN", "value": "MIN" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "sortDirection": "ASC",
       "sysparam_query": "state!=closed^cmdb_ci=$ci",
       "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$allMetrics", "value": "$allMetrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-lightbulb-o\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# Open Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% CI Binding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci!=NULL^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "% Anomalies",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS^event_class=anomaly",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "9999",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ciIN$nestedCIS^state=1",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "title": "% Incidents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "maintenance",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "incident!=NULL^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "state",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Top 10 Sources",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "source",
     "rowLimit": "10",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 6 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-fire\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Major Incidents</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "# P1 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=1^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "# P2 Tickets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "incident.priority",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "cmdb_ci.name!=NULL^incident!=NULL^incident.priority=2^maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 9 },
   "options": {
    "content": "<p></p>\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-bullseye\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Clustering Insights</span></span></span></a></p>"
   },
   "targets": [
    {
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "sys_id",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "group_source",
     "rowLimit": "9999",
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^state!=closed^cmdb_ciIN$nestedCIS",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 12 },
   "options": {
    "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-exclamation-triangle\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Active Alerts</span></span></span></a></p>"
   }
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$cis", "value": "$cis" }
      },
      {
       "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$supportGroup", "value": "$supportGroup" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "cacheOverride": "5s",
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "3000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "maintenance=false^cmdb_ciIN$nestedCIS"
    }
   ]
  },
  {
   "title": "Topology and Tags",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 29 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-connectdevelop\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Topology</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 8, "x": 12, "y": 29 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-tags\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Tags</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "title": "Topology",
     "type": "novatec-sdg-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "9999",
       "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
       "selectedServiceList": { "label": "$ci", "value": "$ci" },
       "sortDirection": "ASC",
       "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    },
    {
     "title": "Tags",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "9999",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
     "repeat": "metric",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        { "label": "$metric", "value": "$metric" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "rowLimit": "1000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "description": "error_message", "label": "Error message", "value": "error_message" },
        { "description": "event_name", "label": "Event name", "value": "event_name" },
        { "description": "payload", "label": "Payload", "value": "payload" },
        { "description": "processed", "label": "Processed", "value": "processed" },
        { "description": "source", "label": "Source", "value": "source" },
        { "description": "state", "label": "State", "value": "state" },
        { "description": "sys_updated_by", "label": "Updated by", "value": "sys_updated_by" },
        { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
       ],
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 23, "x": 0, "y": 32 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-certificate\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">TLS Certificate Tasks</span></span></span></a></p>"
     }
    },
    {
     "title": "Expired Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^certificate_expiration_date<=javascript:gs.beginningOfToday()^cmdb_ciIN$ci^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Renewal Tasks",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" }
        },
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" }, "4": { "label": "AND", "value": "^" } },
        { "1": { "label": "cmdb_ci", "value": "cmdb_ci" }, "2": { "description": "IN", "label": "is one of", "value": "IN" }, "3": { "label": "$nestedCIS", "value": "$nestedCIS" }, "4": { "label": "AND", "value": "^" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "priority", "value": "priority" },
        { "label": "state", "value": "state" },
        { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
        { "label": "cmdb_ci", "value": "cmdb_ci" },
        { "label": "cmdb_ci.sys_id", "value": "cmdb_ci.sys_id" },
        { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
        { "description": "root_issuer", "label": "Root issuer", "value": "root_issuer" },
        { "label": "cmdb_ci.subject_organization", "value": "cmdb_ci.subject_organization" },
        { "label": "cmdb_ci.is_self_signed", "value": "cmdb_ci.is_self_signed" }
       ],
       "sortDirection": "ASC",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 33 },
     "options": {
      "content": "\n<p><a><span style=\"color: #84c9fb;\"><span style=\"font-size: 16pt;\"><i class=\"fa fa-table\"></i>&nbsp;&nbsp;<span style=\"color: #f6f6f6;\">Metric Checks</span></span></span></a></p>"
     },
     "targets": [
      {
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    },
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}