{
 "title": "Generic CI Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   { "name": "namespaces" },
   {
    "name": "relationshipType",
    "query": {}
   },
   {
    "name": "image",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "$ci", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "sysparam_option1": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_ci", "label": "Configuration Item", "value": "cmdb_ci" }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "repeat": "allMetrics",
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": { "label": "$allMetrics", "value": "$allMetrics" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Active Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Active Noise Reduction ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregateColumn": "event_count",
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "state",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedAggregateType": { "label": "SUM", "value": "SUM" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
     "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Incidents Last 30 Days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
     "service": "$service",
     "source": "$source",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
     "tableName": { "label": "Incident (incident)", "value": "incident" }
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
   "targets": [
    {
     "aggregateColumn": "number",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
     "selectedAggregateType": { "label": "COUNT", "value": "COUNT" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sortDirection": "ASC",
     "sysparam_query": "state!=Closed^group_source=9^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
      { "description": "name", "label": "Name", "value": "name" },
      { "description": "sys_class_name", "label": "Class", "value": "sys_class_name" }
     ],
     "sortDirection": "ASC",
     "tableName": { "description": "cmdb_ci", "label": "Configuration Item", "value": "cmdb_ci" }
    }
   ]
  },
  {
   "title": "Sophie ML Anomaly Detection",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 6 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sn_extra_data.category", "label": "Extra data => Category", "value": "sn_extra_data.category" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "2", "value": "2" }
      },
      {
       "1": { "description": "cmdb_ci.sys_id", "label": "Configuration item => Sys ID", "value": "cmdb_ci.sys_id" },
       "2": { "description": "IN", "label": "is one of", "value": "IN" },
       "3": { "label": "$ci", "value": "$ci" },
       "4": { "label": "AND", "value": "^" }
      },
      { "1": { "description": "state", "label": "State", "value": "state" }, "2": { "description": "!=", "label": "is not", "value": "!=" }, "3": { "label": "Closed", "value": "Closed" }, "4": { "label": "AND", "value": "^" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "number", "label": "Number", "value": "number" },
      { "description": "sn_extra_data.explanation", "label": "Extra data => Explanation", "value": "sn_extra_data.explanation" },
      { "description": "sn_extra_data.anomaly", "label": "Extra data => Anomaly", "value": "sn_extra_data.anomaly" }
     ],
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    },
    {
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alerts", "label": "Alerts", "value": "Alerts" },
     "sysparam_query": "sn_extra_data.category=2^cmdb_ciIN$anomalyCIS"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricName": "$metricName",
     "metricType": "$metricType",
     "rowLimit": "2000",
     "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
     "selectedAlertTypeList": {
      "description": "Ignore CI selection and use sysparam_query",
      "label": "None",
      "value": "None"
     },
     "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
     "service": "$service",
     "sortDirection": "ASC",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "novatec-sdg-panel",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": { "description": "Get Topology", "label": "Topology", "value": "Topology" },
       "selectedServiceList": { "label": "$ci", "value": "$ci" },
       "sortDirection": "ASC",
       "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
       "topology_child_depth": "$childTopo",
       "topology_parent_depth": "$parentTopo"
      }
     ]
    },
    {
     "title": "Tags",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is", "value": "=" }
       ],
       "sysparam_option3": [
        { "label": "$ci", "value": "$ci" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 38 },
     "options": {
      "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
     },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "service": "$service",
       "source": "$source"
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "repeat": "metric",
     "targets": [
      {
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": { "label": "$metric", "value": "$metric" },
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": { "label": "ServiceNow Event Management", "value": "ServiceNow Event Management" },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "rowLimit": "1000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "description": "error_message", "label": "Error message", "value": "error_message" },
        { "description": "event_name", "label": "Event name", "value": "event_name" },
        { "description": "payload", "label": "Payload", "value": "payload" },
        { "description": "processed", "label": "Processed", "value": "processed" },
        { "description": "source", "label": "Source", "value": "source" },
        { "description": "state", "label": "State", "value": "state" },
        { "description": "sys_updated_by", "label": "Updated by", "value": "sys_updated_by" },
        { "description": "sys_updated_on", "label": "Updated", "value": "sys_updated_on" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
       ],
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "TLS Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^certificate_expiration_date<=javascript:gs.beginningOfToday()^cmdb_ciIN$ci^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Expiring Certificates",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basic_sysparam": [
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" } },
        {
         "1": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
         "2": { "description": "<=", "label": "less than or is", "value": "<=" },
         "3": {
          "label": "javascript:gs.beginningOfToday()",
          "value": "javascript:gs.beginningOfToday()"
         },
         "4": { "label": "AND", "value": "^" }
        },
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "grafanaTimerangeColumn": { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "sortDirection": "ASC",
       "sysparam_query": "active=true^certificate_task_type=renewal^cmdb_ciIN$nestedCIS",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    },
    {
     "title": "Renewal Tasks",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "Renewal", "value": "renewal" }
        },
        { "1": { "label": "active", "value": "active" }, "2": { "description": "=", "label": "is", "value": "=" }, "3": { "label": "true", "value": "true" }, "4": { "label": "AND", "value": "^" } },
        { "1": { "label": "cmdb_ci", "value": "cmdb_ci" }, "2": { "description": "IN", "label": "is one of", "value": "IN" }, "3": { "label": "$nestedCIS", "value": "$nestedCIS" }, "4": { "label": "AND", "value": "^" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "selectedtableColumns": [
        { "label": "number", "value": "number" },
        { "label": "priority", "value": "priority" },
        { "label": "state", "value": "state" },
        { "description": "certificate_expiration_date", "label": "Certificate expiration date", "value": "certificate_expiration_date" },
        { "label": "assigned_to", "value": "assigned_to" },
        { "description": "certificate_task_type", "label": "Certificate task type", "value": "certificate_task_type" },
        { "label": "cmdb_ci", "value": "cmdb_ci" },
        { "label": "cmdb_ci.sys_id", "value": "cmdb_ci.sys_id" },
        { "label": "cmdb_ci.sys_class_name", "value": "cmdb_ci.sys_class_name" },
        { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
        { "description": "root_issuer", "label": "Root issuer", "value": "root_issuer" },
        { "label": "cmdb_ci.subject_organization", "value": "cmdb_ci.subject_organization" },
        { "label": "cmdb_ci.is_self_signed", "value": "cmdb_ci.is_self_signed" }
       ],
       "sortDirection": "ASC",
       "tableName": {
        "description": "sn_disco_certmgmt_certificate_task",
        "label": "Certificate task",
        "value": "sn_disco_certmgmt_certificate_task"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}