{
 "title": "Kubernetes 360 Degree View 2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "namespace" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$ci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "label": "last_discovered,sys_class_name,operational_status,name,namespace,selector,monitor,sys_id,discovery_source,fault_count,first_discovered,install_status,sys_created_on,sys_created_by,sys_updated_on,sys_updated_by,k8s_uid,u_url",
       "value": "last_discovered,sys_class_name,operational_status,name,namespace,selector,monitor,sys_id,discovery_source,fault_count,first_discovered,install_status,sys_created_on,sys_created_by,sys_updated_on,sys_updated_by,k8s_uid,u_url"
      }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "1", "value": "1" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_ci_kubernetes_cluster", "label": "Kubernetes Cluster", "value": "cmdb_ci_kubernetes_cluster" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "label": "last_discovered,sys_class_name,operational_status,name,namespace,selector,monitor,sys_id,discovery_source,fault_count,first_discovered,install_status,sys_created_on,sys_created_by,sys_updated_on,sys_updated_by,k8s_uid,u_url",
       "value": "last_discovered,sys_class_name,operational_status,name,namespace,selector,monitor,sys_id,discovery_source,fault_count,first_discovered,install_status,sys_created_on,sys_created_by,sys_updated_on,sys_updated_by,k8s_uid,u_url"
      }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "1", "value": "1" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": { "description": "cmdb_ci_kubernetes_node", "label": "Kubernetes Node", "value": "cmdb_ci_kubernetes_node" }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "1",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "sysparam_count": 1,
     "sysparam_option1": [
      { "description": "operational_status", "label": "Operational status", "value": "operational_status" },
      { "description": "sys_id", "label": "Sys ID", "value": "sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "1", "value": "1" },
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      {}
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "basicSysparm": [
      {
       "column": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "operator": { "description": "=", "label": "is", "value": "=" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
      { "description": "key", "label": "Key", "value": "key" },
      { "description": "value", "label": "Value", "value": "value" },
      { "description": "sys_created_on", "label": "Created", "value": "sys_created_on" }
     ],
     "sortDirection": "ASC",
     "sysparam_option1": [
      { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "$allMetrics",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "repeat": "allMetrics",
   "targets": [
    {
     "basic_sysparam": [
      {}
     ],
     "depends_on_toggle": "$dependsOnFilter",
     "getAlertCount": { "label": "No", "value": "false" },
     "metricAnomaly": "false",
     "metricName": "$allMetrics",
     "metricType": "*",
     "rowLimit": "9999",
     "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
     "selectedMetricNameList": [
      { "label": "$allMetrics", "value": "$allMetrics" }
     ],
     "selectedMetricTypeList": [
      { "label": "*", "value": "*" }
     ],
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "selectedServiceList": {
      "__isNew__": true,
      "label": "$service",
      "value": "$service"
     },
     "selectedSourceList": [
      { "label": "$ci", "value": "$ci" }
     ],
     "service": "$service",
     "sortDirection": "ASC",
     "source": "$ci",
     "sysparam_option4": [
      { "label": "", "value": "" }
     ]
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {
       "1": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "excludedClasses": [
      { "label": "$filterClasses", "value": "$filterClasses" }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "relationshipTypes": [
      { "label": "$relationshipType", "value": "$relationshipType" }
     ],
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Show relationships in the node graph panel",
      "label": "Node Graph",
      "value": "Node_Graph"
     },
     "selectedServiceList": { "label": "$ci", "value": "$ci" },
     "sortDirection": "ASC",
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses^parent.namespaceLIKE$namespace^child.namespaceLIKE$namespace",
     "topology_child_depth": "$childTopo",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "options": {
    "content": "❗If the topology panel is returning an error or loading for a long time, you may be requesting too much data at once. <br/> Try adding more classes to the exclude list or lower your parent/child search levels to refine the search\n           "
   },
   "targets": [
    {
     "depends_on_toggle": "$dependsOnFilter",
     "metricName": "$metricName",
     "metricType": "$metricType",
     "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
     "service": "$service",
     "source": "$source"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "depends_on_toggle": "$dependsOnFilter",
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      },
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ci.sys_idIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" }
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "depends_on_toggle": "$dependsOnFilter",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ci.sys_idIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" }
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$cis", "value": "$cis" }
        },
        {
         "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$supportGroup", "value": "$supportGroup" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "rowLimit": "3000",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Cloud Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cloud Events",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sysparam_option1": [
        { "description": "ci.sys_id", "label": "Configuration Item => Sys ID", "value": "ci.sys_id" }
       ],
       "sysparam_option2": [
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sn_cmp_cloud_event", "label": "Cloud Event", "value": "sn_cmp_cloud_event" }
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 34 },
     "repeat": "metric",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$metric", "value": "$metric" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Change/Deployment Records",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$service", "value": "$service" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "selectedChangeTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Changes", "label": "Changes", "value": "Changes" },
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ciIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}