{
 "title": "vCenter CI 360 Degree View",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ciClasses",
    "query": {}
   },
   {
    "name": "ci",
    "query": {}
   },
   {
    "name": "metric",
    "label": "KPI",
    "query": {}
   },
   {
    "name": "allMetrics",
    "query": {}
   },
   { "name": "childTopo", "label": "child_topo_levels", "query": "0,1,2,3,4,5" },
   { "name": "parentTopo", "label": "parent_topo_levels", "query": "0,1,2,3,4,5" },
   {
    "name": "filterClasses",
    "label": "Exclude Classes",
    "query": {}
   },
   {
    "name": "nestedCIS",
    "query": {}
   },
   {
    "name": "relationshipType",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$ci",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "basic_sysparam": [
      {
       "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "label": "cpus,disks,disks_size,first_discovered,fqdn,guest_os_fullname,guest_reconciled,ip_address,last_discovered,location,memory,name,nics,object_id,operational_status,state,sys_class_name,sys_id,sys_updated_by,sys_updated_on,u_critical,u_managedbygroup,u_support_level,u_used_for,u_watchlist,vcenter_ref,vcenter_uuid,vm_instance_uuid",
       "value": "cpus,disks,disks_size,first_discovered,fqdn,guest_os_fullname,guest_reconciled,ip_address,last_discovered,location,memory,name,nics,object_id,operational_status,state,sys_class_name,sys_id,sys_updated_by,sys_updated_on,u_critical,u_managedbygroup,u_support_level,u_used_for,u_watchlist,vcenter_ref,vcenter_uuid,vm_instance_uuid"
      }
     ],
     "sortBy": { "description": "name", "label": "Name", "value": "name" },
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "vcenter_ref.sys_id", "label": "vCenter Reference => Sys ID", "value": "vcenter_ref.sys_id" },
      { "description": "guest_os_fullname", "label": "Guest OS Name", "value": "guest_os_fullname" },
      { "description": "u_used_for", "label": "Used For", "value": "u_used_for" },
      { "description": "location.sys_id", "label": "Location => Sys ID", "value": "location.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$vCenter", "value": "$vCenter" },
      { "label": "$os", "value": "$os" },
      { "label": "$used_for", "value": "$used_for" },
      { "label": "$location", "value": "$location" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "cmdb_ci_vmware_instance",
      "label": "VMware Virtual Machine Instance",
      "value": "cmdb_ci_vmware_instance"
     }
    },
    {
     "basic_sysparam": [
      {
       "1": { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "$ci", "value": "$ci" }
      },
      {
       "1": {
        "description": "service_id.service_classification",
        "label": "Service Id => Service classification",
        "value": "service_id.service_classification"
       },
       "2": { "description": "=", "label": "is", "value": "=" },
       "3": { "label": "Application Service", "value": "Application Service" },
       "4": { "label": "AND", "value": "^" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      { "description": "ci_id.sys_id", "label": "Configuration Item => Sys ID", "value": "ci_id.sys_id" },
      { "description": "service_id.name", "label": "Service Id => Name", "value": "service_id.name" },
      { "description": "service_id.sys_id", "label": "Service Id => Sys ID", "value": "service_id.sys_id" }
     ],
     "sysparam_count": 2,
     "sysparam_option1": [
      { "description": "state", "label": "State", "value": "state" },
      { "description": "vcenter_ref.sys_id", "label": "vCenter Reference => Sys ID", "value": "vcenter_ref.sys_id" },
      { "description": "guest_os_fullname", "label": "Guest OS Name", "value": "guest_os_fullname" },
      { "description": "u_used_for", "label": "Used For", "value": "u_used_for" },
      { "description": "location.sys_id", "label": "Location => Sys ID", "value": "location.sys_id" }
     ],
     "sysparam_option2": [
      { "description": "=", "label": "is", "value": "=" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" },
      { "description": "IN", "label": "is one of", "value": "IN" }
     ],
     "sysparam_option3": [
      { "label": "on", "value": "on" },
      { "label": "$vCenter", "value": "$vCenter" },
      { "label": "$os", "value": "$os" },
      { "label": "$used_for", "value": "$used_for" },
      { "label": "$location", "value": "$location" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" },
      { "label": "AND", "value": "^" }
     ],
     "tableName": {
      "description": "svc_ci_assoc",
      "label": "Service Configuration Item Association",
      "value": "svc_ci_assoc"
     }
    },
    {
     "aggregateColumn": "severity",
     "basic_sysparam": [
      { "1": { "description": "name", "label": "Name", "value": "name" }, "2": { "description": "LIKE", "label": "contains", "value": "LIKE" }, "3": { "label": "$nameSearch", "value": "$nameSearch" } }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "groupBy": "cmdb_ci.sys_id",
     "selectedAggregateType": { "label": "MIN", "value": "MIN" },
     "selectedQueryCategory": {
      "description": "Group by and apply aggregate functions to table data",
      "label": "Aggregate",
      "value": "Aggregate"
     },
     "sysparam_query": "state!=closed^cmdb_ci=$ci",
     "tableName": { "description": "em_alert", "label": "Alert", "value": "em_alert" }
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "basicSysparm": [
      {}
     ],
     "basic_sysparam": [
      {}
     ],
     "excludedClasses": [
      { "label": "$filterClasses", "value": "$filterClasses" }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "relationshipTypes": [
      { "label": "$relationshipType", "value": "$relationshipType" }
     ],
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Show relationships in the node graph panel",
      "label": "Node Graph",
      "value": "Node_Graph"
     },
     "selectedServiceList": { "label": "$ci", "value": "$ci" },
     "sortDirection": "ASC",
     "sysparam_query": "typeIN$relationshipType^parent.sys_class_nameNOT IN$filterClasses^child.sys_class_nameNOT IN$filterClasses",
     "topology_child_depth": "$childTopo",
     "topology_parent_depth": "$parentTopo"
    }
   ]
  },
  {
   "title": "Tags",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "basicSysparm": [
      {
       "column": { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" },
       "operator": { "description": "=", "label": "is", "value": "=" },
       "separator": { "label": "AND", "value": "^" },
       "value": { "label": "$ci", "value": "$ci" }
      }
     ],
     "getAlertCount": { "label": "No", "value": "false" },
     "rowLimit": "2000",
     "selectedQueryCategory": {
      "description": "Choose your own table to gather data from",
      "label": "Table",
      "value": "Table"
     },
     "selectedtableColumns": [
      {
       "description": "configuration_item.sys_class_name",
       "label": "Configuration item => Class",
       "value": "configuration_item.sys_class_name"
      },
      { "description": "configuration_item.name", "label": "Configuration item => Name", "value": "configuration_item.name" },
      { "description": "key", "label": "Key", "value": "key" },
      { "description": "value", "label": "Value", "value": "value" }
     ],
     "sortDirection": "ASC",
     "sysparam_option1": [
      { "description": "configuration_item.sys_id", "label": "Configuration item => Sys ID", "value": "configuration_item.sys_id" }
     ],
     "sysparam_option2": [
      { "label": "is", "value": "=" }
     ],
     "sysparam_option3": [
      { "label": "$ci", "value": "$ci" }
     ],
     "sysparam_option4": [
      { "label": "", "value": "" }
     ],
     "tableName": { "description": "cmdb_key_value", "label": "Key Value", "value": "cmdb_key_value" },
     "topology_child_depth": "3",
     "topology_parent_depth": "3"
    }
   ]
  },
  {
   "title": "Change Records",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$nestedCIS", "value": "$nestedCIS" } }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "tableName": { "description": "change_request", "label": "Change Request", "value": "change_request" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Overall Noise Reduction Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregateColumn": "event_count",
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$nestedCIS", "value": "$nestedCIS" } }
       ],
       "basic_sysparam": [
        {
         "1": { "label": "vmwarevm_vmware_vm_instance", "value": "vmwarevm_vmware_vm_instance" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "groupBy": "state",
       "metricName": "$metricName",
       "metricType": "$metricType",
       "rowLimit": "2000",
       "selectedAggregateType": { "label": "SUM", "value": "SUM" },
       "selectedQueryCategory": {
        "description": "Group by and apply aggregate functions to table data",
        "label": "Aggregate",
        "value": "Aggregate"
       },
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      },
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$nestedCIS", "value": "$nestedCIS" } }
       ],
       "basic_sysparam": [
        {
         "1": { "label": "vmwarevm_vmware_vm_instance", "value": "vmwarevm_vmware_vm_instance" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "rowLimit": "2000",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^group_source!=5^cmdb_ciIN$nestedCIS^state!=Closed",
       "tableName": { "label": "Alert (em_alert)", "value": "em_alert" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    },
    {
     "title": "Incidents Last 30 Days",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "basicSysparm": [
        { "column": { "label": "cmdb_ci", "value": "cmdb_ci" }, "operator": { "label": "IN", "value": "IN" }, "value": { "label": "$nestedCIS", "value": "$nestedCIS" } }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "rowLimit": "2000",
       "selectedQueryCategory": { "description": "Get row count from query", "label": "Row Count", "value": "Row_Count" },
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$source",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "sys_created_on>=javascript:gs.beginningOfLast30Days()^cmdb_ciIN$nestedCIS",
       "tableName": { "label": "Incident (incident)", "value": "incident" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "description": "sys_id", "label": "Sys ID", "value": "sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$cis", "value": "$cis" }
        },
        {
         "1": { "description": "support_group.sys_id", "label": "Support group => Sys ID", "value": "support_group.sys_id" },
         "2": { "description": "IN", "label": "is one of", "value": "IN" },
         "3": { "label": "$supportGroup", "value": "$supportGroup" },
         "4": { "label": "AND", "value": "^" }
        }
       ],
       "depends_on_toggle": "$dependsOnFilter",
       "getAlertCount": { "label": "No", "value": "false" },
       "metricName": "$metricName",
       "metricType": "$metricType",
       "rowLimit": "3000",
       "selectedAlertStateList": { "description": "Get Open and Reopen Alerts", "label": "Active", "value": "Active" },
       "selectedAlertTypeList": {
        "description": "Ignore CI selection and use sysparam_query",
        "label": "None",
        "value": "None"
       },
       "selectedQueryCategory": { "description": "Get Alert", "label": "Alerts", "value": "Alerts" },
       "service": "$service",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "sysparam_query": "cmdb_ci.sys_idIN$nestedCIS"
      }
     ]
    }
   ]
  },
  {
   "title": "vCenter Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "basicSysparm": [
        {
         "column": { "description": "instance", "label": "Instance", "value": "instance" },
         "operator": { "description": "IN", "label": "is one of", "value": "IN" },
         "separator": { "label": "AND", "value": "^" },
         "value": { "label": "$nestedCIS", "value": "$nestedCIS" }
        }
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "rowLimit": "2000",
       "selectedQueryCategory": {
        "description": "Choose your own table to gather data from",
        "label": "Table",
        "value": "Table"
       },
       "sortDirection": "ASC",
       "sysparam_option1": [
        { "description": "instance", "label": "Instance", "value": "instance" }
       ],
       "sysparam_option2": [
        { "description": "IN", "label": "is one of", "value": "IN" }
       ],
       "sysparam_option3": [
        { "label": "$nestedCIS", "value": "$nestedCIS" }
       ],
       "sysparam_option4": [
        { "label": "", "value": "" }
       ],
       "tableName": { "description": "sysevent", "label": "Event", "value": "sysevent" },
       "topology_child_depth": "3",
       "topology_parent_depth": "3"
      }
     ]
    }
   ]
  },
  {
   "title": "All Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$allMetrics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "repeat": "allMetrics",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "false",
       "metricName": "$allMetrics",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "$allMetrics", "value": "$allMetrics" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    },
    {
     "title": "$metric",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 29 },
     "repeat": "metric",
     "targets": [
      {
       "basic_sysparam": [
        {}
       ],
       "getAlertCount": { "label": "No", "value": "false" },
       "metricAnomaly": "true",
       "metricName": "$metric",
       "metricType": "*",
       "rowLimit": "9999",
       "selectedMetricAnomalyList": { "description": "", "label": "true", "value": "true" },
       "selectedMetricNameList": [
        { "label": "$metric", "value": "$metric" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "sortDirection": "ASC",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Checks Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Metrics Table",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "basic_sysparam": [
        {
         "1": { "label": "vmwarevm_vmware_vm_instance", "value": "vmwarevm_vmware_vm_instance" },
         "2": { "description": "=", "label": "is", "value": "=" },
         "3": { "label": "$ci", "value": "$ci" }
        }
       ],
       "metricAnomaly": "false",
       "metricName": "*",
       "metricType": "*",
       "selectedMetricAnomalyList": { "description": "", "label": "false", "value": "false" },
       "selectedMetricNameList": [
        { "label": "*", "value": "*" }
       ],
       "selectedMetricTypeList": [
        { "label": "*", "value": "*" }
       ],
       "selectedQueryCategory": { "description": "Get Timeseries metrics.", "label": "Metrics", "value": "Metrics" },
       "selectedServiceList": {
        "__isNew__": true,
        "label": "$service",
        "value": "$service"
       },
       "selectedSourceList": [
        { "label": "$ci", "value": "$ci" }
       ],
       "service": "$service",
       "source": "$ci",
       "sysparam_option4": [
        { "label": "", "value": "" }
       ]
      }
     ]
    }
   ]
  }
 ]
}